name: blw_attend_ease
description: "A new Flutter project for BLW Employees attendance"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+1
  path: ^1.8.3
  intl: ^0.18.1
  excel: ^2.0.6
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2
  geolocator: ^11.0.0

  geocoding: ^2.2.0
  flutter_local_notifications: ^17.1.2
  # File opening package
  open_filex: ^4.4.0

  # Permissions package
  permission_handler: ^11.3.1

  # UI icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: true
    ios: true
    image_path: "assets/app_icon.png"



flutter:
  assets:
    - assets/blw_logo.png
  uses-material-design: true
